use strict;
use warnings;
use Test::More 0.88;
# This is a relatively nice way to avoid Test::NoWarnings breaking our
# expectations by adding extra tests, without using no_plan.  It also helps
# avoid any other test module that feels introducing random tests, or even
# test plans, is a nice idea.
our $success = 0;
END { $success && done_testing; }

# List our own version used to generate this
my $v = "\nGenerated by Dist::Zilla::Plugin::ReportVersions::Tiny v1.08\n";

eval {                     # no excuses!
    # report our Perl details
    my $want = 'v5.10.1';
    $v .= "perl: $] (wanted $want) on $^O from $^X\n\n";
};
defined($@) and diag("$@");

# Now, our module version dependencies:
sub pmver {
    my ($module, $wanted) = @_;
    $wanted = " (want $wanted)";
    my $pmver;
    eval "require $module;";
    if ($@) {
        if ($@ =~ m/Can't locate .* in \@INC/) {
            $pmver = 'module not found.';
        } else {
            diag("${module}: $@");
            $pmver = 'died during require.';
        }
    } else {
        my $version;
        eval { $version = $module->VERSION; };
        if ($@) {
            diag("${module}: $@");
            $pmver = 'died during VERSION check.';
        } elsif (defined $version) {
            $pmver = "$version";
        } else {
            $pmver = '<undef>';
        }
    }

    # So, we should be good, right?
    return sprintf('%-45s => %-10s%-15s%s', $module, $pmver, $wanted, "\n");
}

eval { $v .= pmver('Carp','any version') };
eval { $v .= pmver('Import::Into','1.001000') };
eval { $v .= pmver('List::MoreUtils','0.23') };
eval { $v .= pmver('Test::CheckDeps','0.002') };
eval { $v .= pmver('Test::More','0.94') };
eval { $v .= pmver('Test::Pod','1.41') };
eval { $v .= pmver('Toolkit','any version') };
eval { $v .= pmver('autolocale','any version') };
eval { $v .= pmver('autovivification','any version') };
eval { $v .= pmver('bareword::filehandles','any version') };
eval { $v .= pmver('criticism','any version') };
eval { $v .= pmver('indirect','any version') };
eval { $v .= pmver('multidimensional','any version') };
eval { $v .= pmver('namespace::autoclean','any version') };
eval { $v .= pmver('namespace::clean','any version') };
eval { $v .= pmver('namespace::functions','any version') };
eval { $v .= pmver('namespace::sweep','any version') };
eval { $v .= pmver('subs::auto','any version') };
eval { $v .= pmver('true','any version') };
eval { $v .= pmver('utf8::all','any version') };
eval { $v .= pmver('vendorlib','any version') };
eval { $v .= pmver('version','0.9901') };


# All done.
$v .= <<'EOT';

Thanks for using my code.  I hope it works for you.
If not, please try and include this output in the bug report.
That will help me reproduce the issue and solve your problem.

EOT

diag($v);
ok(1, "we really didn't test anything, just reporting data");
$success = 1;

# Work around another nasty module on CPAN. :/
no warnings 'once';
$Template::Test::NO_FLUSH = 1;
exit 0;
